services:
    urpuppy:
        build:
            context: .
        ports:
            - "8000:8000"
        environment:
            WITH_SSR: true
            WITH_HORIZON: true
            WITH_SCHEDULER: true
        volumes:
          - .:/var/www/html
          - /var/run/docker.sock:/var/run/docker.sock
    selenium:
        image: selenium/standalone-chrome:131.0.6778.204-chromedriver-131.0.6778.204
        volumes:
          - /dev/shm:/dev/shm
        ports:
          - "4444:4444"
          - "7900:7900"
    postgres:
        image: postgres:16-alpine
        ports:
            - "5443:5432"
        volumes:
          - pgalpine:/var/lib/postgresql/data
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - POSTGRES_PASSWORD=Asakaboi35
          - POSTGRES_USER=urpuppy
          - POSTGRES_DB=urpuppy

    redis:
        image: redis:alpine

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
          - postgres
        ports:
          - "7777:80"
        volumes:
          - pgadmin_datanew:/var/lib/pgadmin
        environment:
          PGADMIN_DEFAULT_EMAIL: mobistyle35@gmail.com
          PGADMIN_DEFAULT_PASSWORD: Asakaboi35

    mailpit:
        image: axllent/mailpit
        volumes:
          - ./data:/data
        ports:
          - 7025:8025

    typesense:
        image: typesense/typesense:27.0.rc21
        environment:
          TYPESENSE_DATA_DIR: /data
          TYPESENSE_API_KEY: masterKey
        volumes:
          - ./typesense:/data
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 8108:8108
        deploy:
          resources:
            limits:
              cpus: "2.0" # 2 cores
              memory: "1g" # 1GB RAM
        ulimits:
           nproc: 50

volumes:
  storage:
  pgalpine:
  pgadmin_datanew:

