services:
    urpuppy:
        build:
            context: .
        ports:
            - "8000:8000"
        networks:
          urpuppy-network:
        environment:
            WITH_SSR: true
            WITH_HORIZON: true
            WITH_SCHEDULER: true
        volumes:
          - .:/var/www/html
          - /var/run/docker.sock:/var/run/docker.sock
    selenium-hub:
          image: selenium/hub:latest
          networks:
            urpuppy-network:
          container_name: selenium-hub
          ports:
            - "4444:4444"
    chrome:
        image: selenium/node-chrome:latest
        networks:
            urpuppy-network:
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444
    firefox:
        image: selenium/node-firefox:latest
        networks:
            urpuppy-network:
        depends_on:
          - selenium-hub
        environment:
          - HUB_HOST=selenium-hub
          - HUB_PORT=4444

    postgres:
        image: postgres:16-alpine
        ports:
            - "5443:5432"
        networks:
          urpuppy-network:
        volumes:
          - pgalpine:/var/lib/postgresql/data
          - /var/run/docker.sock:/var/run/docker.sock
        environment:
          - POSTGRES_PASSWORD=Asakaboi35
          - POSTGRES_USER=urpuppy
          - POSTGRES_DB=urpuppy

    redis:
        image: redis:alpine
        networks:
          urpuppy-network:

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        depends_on:
          - postgres
        ports:
          - "7777:80"
        volumes:
          - pgadmin_datanew:/var/lib/pgadmin
        networks:
          urpuppy-network:
        environment:
          PGADMIN_DEFAULT_EMAIL: mobistyle35@gmail.com
          PGADMIN_DEFAULT_PASSWORD: Asakaboi35

    mailpit:
        image: axllent/mailpit
        container_name: mailpit
        volumes:
          - ./data:/data
        networks:
          urpuppy-network:
        ports:
          - 7025:8025

    typesense:
        image: typesense/typesense:27.0.rc21
        environment:
          TYPESENSE_DATA_DIR: /data
          TYPESENSE_API_KEY: masterKey
        volumes:
          - ./typesense:/data
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 8108:8108
        networks:
          urpuppy-network:
        deploy:
          resources:
            limits:
              cpus: "2.0" # 2 cores
              memory: "1g" # 1GB RAM
        ulimits:
           nproc: 50

volumes:
  storage:
  pgalpine:
  pgadmin_datanew:

networks:
  urpuppy-network:
